name = "GregTech Odyssey"
version = "0.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ad24be7f9f748e5df2a88176c3069362d305260692f12e1fbb2a292335d1c17"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
